server:
  shutdown : graceful

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    name: "mysql"
    url: "jdbc:log4jdbc:mysql://localhost:3306/db_example?characterEncoding=utf8&allowMultiQueries=true&verifyServerCertificate=false&serverTimezone=GMT%2B8&useSSL=false"
    username: "root"
    password: "Admin@1278300799"
    driver-class-name: "net.sf.log4jdbc.DriverSpy"
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 50
      ## 空闲连接存活最大时间，默认600000（10分钟）
      # idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 100
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 28000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect



logging:
  config: classpath:logback-test.xml